# Generated by Django 4.1.1 on 2023-04-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organization_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_user',
            old_name='username',
            new_name='user',
        ),
    ]
