# Generated by Django 4.1.1 on 2023-10-19 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_username_member_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='Organization', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(default='shop', max_length=25),
            preserve_default=False,
        ),
    ]
