# Generated by Django 4.1.1 on 2023-03-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organization_location'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='shipment_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.location', to_field='city'),
        ),
        migrations.AddField(
            model_name='bill_detail',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
