# Generated by Django 4.1.1 on 2023-04-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_username_member_user_user'),
        ('purchase', '0002_bill_shipment_location_bill_detail_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('organization', 'year', 'bill_no', 'bill_type')},
        ),
    ]
