# Generated by Django 4.1.1 on 2023-04-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_username_member_user_user'),
        ('purchase', '0003_alter_bill_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='vendor',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_rcvr_org',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='rcvr_org_aprv_usr',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='shipment_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.location', to_field='city'),
        ),
    ]
