# Generated by Django 4.1.1 on 2023-04-08 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_username_member_user_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0004_remove_bill_vendor_bill_rcvr_org_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_rcvr_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rcvr_org_aprv_usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='Bill_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(default=None)),
                ('bill_type', models.CharField(default='PURCHASE', max_length=9)),
                ('total', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('payment', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('year', models.IntegerField(default=1401)),
                ('date', models.DateField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name')),
            ],
            options={
                'unique_together': {('organization', 'year', 'bill_no', 'bill_type')},
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='year',
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.bill_transactions'),
        ),
    ]
