# Generated by Django 4.1.1 on 2023-04-08 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_username_member_user_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0005_alter_bill_unique_together_alter_bill_rcvr_org_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill_Transactions',
            new_name='Bill_Transaction',
        ),
    ]
