# Generated by Django 4.1.1 on 2023-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_bill_bill_no_bill_bill_type_bill_creator_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_detail',
            name='profit',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
