# Generated by Django 4.1.1 on 2023-04-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0003_rename_username_member_user_user'),
        ('purchase', '0008_bill_detail_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.bill')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.bill')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
