# Generated by Django 4.1.1 on 2023-04-30 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_username_member_user_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0009_bill_receiver_bill_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_rcvr_org',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rcvr_org_aprv_usr',
        ),
        migrations.RemoveField(
            model_name='bill_receiver',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='bill_receiver',
            name='user',
        ),
        migrations.AddField(
            model_name='bill_receiver',
            name='approval_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bill_receiver',
            name='approval_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='bill_receiver',
            name='bill_rcvr_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name'),
        ),
        migrations.AddField(
            model_name='bill_receiver',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Bill_Payer',
        ),
    ]
