# Generated by Django 4.1.1 on 2023-05-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_alter_bill_receiver_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_description',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchase.bill'),
        ),
    ]
