# Generated by Django 4.1.1 on 2024-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_remove_bill_detail_profit_bill_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
