# Generated by Django 4.1.1 on 2024-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_alter_bill_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_detail',
            name='profit',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
