# Generated by Django 4.1.1 on 2023-04-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_username_member_user_user'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='store',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('organization', 'name', 'location')},
        ),
    ]
