# Generated by Django 4.1.1 on 2023-04-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_store_unique_together_store_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='column',
        ),
        migrations.RemoveField(
            model_name='product',
            name='row',
        ),
        migrations.CreateModel(
            name='Row_Column_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
        ),
    ]
