# Generated by Django 4.1.1 on 2023-04-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_column_remove_product_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row_column_address',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
