# Generated by Django 4.1.1 on 2023-04-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_row_column_address_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_amount_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_requirement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchased_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.CreateModel(
            name='Product_Price_Detial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_price', models.IntegerField(default=0, null=True)),
                ('prev_purchased_price', models.IntegerField(default=0, null=True)),
                ('selling_price', models.IntegerField(default=0, null=True)),
                ('prev_selling_price', models.IntegerField(default=0, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Detial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('minimum_requirement', models.IntegerField()),
                ('item_amount_available', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
