# Generated by Django 4.1.1 on 2023-04-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_detail_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Price_Detial',
            new_name='Product_Price',
        ),
    ]
