# Generated by Django 4.1.1 on 2023-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_product_price_detial_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_detail',
            old_name='item_amount_available',
            new_name='crnt_amt',
        ),
        migrations.RenameField(
            model_name='product_detail',
            old_name='detail',
            new_name='descrip',
        ),
        migrations.RenameField(
            model_name='product_detail',
            old_name='minimum_requirement',
            new_name='min_req',
        ),
        migrations.RenameField(
            model_name='product_price',
            old_name='prev_purchased_price',
            new_name='prch_prc',
        ),
        migrations.RenameField(
            model_name='product_price',
            old_name='prev_selling_price',
            new_name='prev_sel_prc',
        ),
        migrations.RenameField(
            model_name='product_price',
            old_name='selling_price',
            new_name='sel_prc',
        ),
        migrations.RemoveField(
            model_name='product_price',
            name='purchased_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product_price',
            name='prev_prch_prc',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
