# Generated by Django 4.1.1 on 2023-10-01 16:17

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Products/y/m/d', validators=[products.models.validate_image]),
        ),
    ]
