# Generated by Django 4.1.1 on 2023-10-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_organization_img_organization_organization_type'),
        ('products', '0012_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_detail',
            old_name='crnt_amt',
            new_name='current_amount',
        ),
        migrations.RenameField(
            model_name='product_detail',
            old_name='min_req',
            new_name='minimum_requirement',
        ),
        migrations.RenameField(
            model_name='product_price',
            old_name='prev_prch_prc',
            new_name='previous_purchased_price',
        ),
        migrations.RenameField(
            model_name='product_price',
            old_name='prev_sel_prc',
            new_name='previous_selling_price',
        ),
        migrations.RenameField(
            model_name='product_price',
            old_name='prch_prc',
            new_name='purchased_price',
        ),
        migrations.RenameField(
            model_name='product_price',
            old_name='sel_prc',
            new_name='selling_price',
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('organization', 'name')},
        ),
        migrations.RemoveField(
            model_name='store',
            name='admin',
        ),
    ]
