# Generated by Django 4.1.1 on 2023-11-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_organization_img_organization_organization_type'),
        ('products', '0013_rename_crnt_amt_product_detail_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('item_name', 'organization')},
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='current_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='minimum_requirement',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
